name: Build Flycast with Emscripten

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout flycast
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake python3

      - name: Clone and install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build Flycast with Emscripten
        run: |
          source emsdk/emsdk_env.sh
          cd flycast
          mkdir build && cd build
          emcmake cmake ..
          emmake make
        shell: bash

      - name: Upload artifacts (wasm, js)
        uses: actions/upload-artifact@v4
        with:
          name: flycast-wasm-output
          path: |
            build/**/*.wasm
            build/**/*.js
